In [ ]:

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt
import pickle

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/train - Copy.csv")

In [ ]:
df.shape

(17302, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17302 entries, 0 to 17301
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    17302 non-null  int64
 1   Age                   17041 non-null  float64
 2   Gender                17302 non-null  object
 3   Annual Income         16638 non-null  float64
 4   Marital Status        17023 non-null  object
 5   Number of Dependents  15696 non-null  float64
 6   Education Level       17302 non-null  object
 7   Occupation            12209 non-null  object
 8   Health Score          16262 non-null  float64
 9   Location              17302 non-null  object
 10  Policy Type           17302 non-null  object
 11  Previous Claims       12062 non-null  float64
 12  Vehicle Age           17300 non-null  float64
 13  Credit Score          15228 non-null  float64
 14  Insurance Duration    17301 non-null  float64
 15  Policy Start Date     17301 non-null  object
 16  Customer Feedback     16084 non-null  object
 17  Smoking Status        17301 non-null  object
 18  Exercise Frequency    17301 non-null  object
 19  Property Type         17301 non-null  object
 20  Premium Amount        17301 non-null  float64
dtypes: float64(9), int64(1), object(11)
memory usage: 2.8+ MB

In [ ]:
df.describe()

,id,Age,Annual Income,Number of Dependents,Health Score,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Premium Amount
count,17302.000000,17041.000000,16638.000000,15696.000000,16262.000000,12062.000000,17300.000000,15228.000000,17301.000000,17301.000000
mean,8650.500000,41.090664,33299.684998,2.006626,25.721214,0.992124,9.545029,591.861571,5.011676,1098.738628
std,4994.801514,13.582566,32607.417738,1.416944,12.192704,0.979190,5.784669,149.710766,2.608320,862.659512
min,0.000000,18.000000,17.000000,0.000000,2.289029,0.000000,0.000000,300.000000,1.000000,20.000000
25%,4325.250000,29.000000,8094.000000,1.000000,16.051821,0.000000,4.000000,467.000000,3.000000,508.000000
50%,8650.500000,41.000000,24107.500000,2.000000,24.674232,1.000000,10.000000,593.000000,5.000000,870.000000
75%,12975.750000,53.000000,44933.000000,3.000000,34.591401,2.000000,15.000000,719.000000,7.000000,1501.000000
max,17301.000000,64.000000,149993.000000,4.000000,58.886035,6.000000,19.000000,849.000000,9.000000,4982.000000

In [ ]:
df.isnull().sum()

id                         0
Age                      261
Gender                     0
Annual Income            664
Marital Status           279
Number of Dependents    1606
Education Level            0
Occupation              5093
Health Score            1040
Location                   0
Policy Type                0
Previous Claims         5240
Vehicle Age                2
Credit Score            2074
Insurance Duration         1
Policy Start Date          1
Customer Feedback       1218
Smoking Status             1
Exercise Frequency         1
Property Type              1
Premium Amount             1
dtype: int64

In [ ]:
df.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,...,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
0,0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,...,2.0,17.0,372.0,5.0,21:39.1,Poor,No,Weekly,House,2869.0
1,1,39.0,Female,31678.0,Divorced,3.0,Master's,NaN,15.569731,Rural,...,1.0,12.0,694.0,2.0,21:39.1,Average,Yes,Monthly,House,1483.0
2,2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,...,1.0,14.0,NaN,3.0,21:39.2,Good,Yes,Weekly,House,567.0
3,3,21.0,Male,141855.0,Married,2.0,Bachelor's,NaN,10.938144,Rural,...,1.0,0.0,367.0,1.0,21:39.2,Poor,Yes,Daily,Apartment,765.0
4,4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,...,0.0,8.0,598.0,4.0,21:39.3,Poor,Yes,Weekly,House,2022.0

In [ ]:
# handling the missing values

for i in df.select_dtypes(include='object').columns:
  df[i].fillna(df[i].mode()[0], inplace=True)

<ipython-input-9-df6e1a6e9e91>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0], inplace=True)

In [ ]:
for i in df.select_dtypes(include=["int64","float64"]).columns:
  df[i] = df[i].fillna(df[i].mean())

In [ ]:
df.isnull().sum()

id                      0
Age                     0
Gender                  0
Annual Income           0
Marital Status          0
Number of Dependents    0
Education Level         0
Occupation              0
Health Score            0
Location                0
Policy Type             0
Previous Claims         0
Vehicle Age             0
Credit Score            0
Insurance Duration      0
Policy Start Date       0
Customer Feedback       0
Smoking Status          0
Exercise Frequency      0
Property Type           0
Premium Amount          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17302 entries, 0 to 17301
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    17302 non-null  int64
 1   Age                   17302 non-null  float64
 2   Gender                17302 non-null  object
 3   Annual Income         17302 non-null  float64
 4   Marital Status        17302 non-null  object
 5   Number of Dependents  17302 non-null  float64
 6   Education Level       17302 non-null  object
 7   Occupation            17302 non-null  object
 8   Health Score          17302 non-null  float64
 9   Location              17302 non-null  object
 10  Policy Type           17302 non-null  object
 11  Previous Claims       17302 non-null  float64
 12  Vehicle Age           17302 non-null  float64
 13  Credit Score          17302 non-null  float64
 14  Insurance Duration    17302 non-null  float64
 15  Policy Start Date     17302 non-null  object
 16  Customer Feedback     17302 non-null  object
 17  Smoking Status        17302 non-null  object
 18  Exercise Frequency    17302 non-null  object
 19  Property Type         17302 non-null  object
 20  Premium Amount        17302 non-null  float64
dtypes: float64(9), int64(1), object(11)
memory usage: 2.8+ MB

In [ ]:
df.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,...,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
0,0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,...,2.0,17.0,372.000000,5.0,21:39.1,Poor,No,Weekly,House,2869.0
1,1,39.0,Female,31678.0,Divorced,3.0,Master's,Self-Employed,15.569731,Rural,...,1.0,12.0,694.000000,2.0,21:39.1,Average,Yes,Monthly,House,1483.0
2,2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,...,1.0,14.0,591.861571,3.0,21:39.2,Good,Yes,Weekly,House,567.0
3,3,21.0,Male,141855.0,Married,2.0,Bachelor's,Self-Employed,10.938144,Rural,...,1.0,0.0,367.000000,1.0,21:39.2,Poor,Yes,Daily,Apartment,765.0
4,4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,...,0.0,8.0,598.000000,4.0,21:39.3,Poor,Yes,Weekly,House,2022.0

In [ ]:
df["Premium Amount"] = np.log1p(df["Premium Amount"])

In [ ]:
x = df.drop("Premium Amount", axis=1)
y = df["Premium Amount"]

In [ ]:
x.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type
0,0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,Premium,2.0,17.0,372.000000,5.0,21:39.1,Poor,No,Weekly,House
1,1,39.0,Female,31678.0,Divorced,3.0,Master's,Self-Employed,15.569731,Rural,Comprehensive,1.0,12.0,694.000000,2.0,21:39.1,Average,Yes,Monthly,House
2,2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,Premium,1.0,14.0,591.861571,3.0,21:39.2,Good,Yes,Weekly,House
3,3,21.0,Male,141855.0,Married,2.0,Bachelor's,Self-Employed,10.938144,Rural,Basic,1.0,0.0,367.000000,1.0,21:39.2,Poor,Yes,Daily,Apartment
4,4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,Premium,0.0,8.0,598.000000,4.0,21:39.3,Poor,Yes,Weekly,House

In [ ]:
y.head()

0    7.962067
1    7.302496
2    6.342121
3    6.641182
4    7.612337
Name: Premium Amount, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.2)

In [ ]:
x_train.shape

(13841, 20)

In [ ]:
y_train.shape

(13841,)

In [ ]:
x_test.shape

(3461, 20)

In [ ]:
y_test.shape

(3461,)

In [ ]:
# Identify numeric and categorical columns
numeric_cols = x.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = x.select_dtypes(include=['object', 'category']).columns.tolist()

In [ ]:
numeric_cols

['id',
 'Age',
 'Annual Income',
 'Number of Dependents',
 'Health Score',
 'Previous Claims',
 'Vehicle Age',
 'Credit Score',
 'Insurance Duration']

In [ ]:
categorical_cols

['Gender',
 'Marital Status',
 'Education Level',
 'Occupation',
 'Location',
 'Policy Type',
 'Policy Start Date',
 'Customer Feedback',
 'Smoking Status',
 'Exercise Frequency',
 'Property Type']

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
# Preprocessor
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numeric_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
])

# Pipeline
model = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42, n_jobs=-1))
])

# Fit model
model.fit(x_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['id', 'Age', 'Annual Income',
                                                   'Number of Dependents',
                                                   'Health Score',
                                                   'Previous Claims',
                                                   'Vehicle Age',
                                                   'Credit Score',
                                                   'Insurance Duration']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Marital Status',
                                                   'Education Level',
                                                   'Occupation', 'Location',
                                                   'Policy Type',
                                                   'Policy Start Date',
                                                   'Customer Feedback',
                                                   'Smoking Status',
                                                   'Exercise Frequency',
                                                   'Property Type'])])),
                ('regressor',
                 RandomForestRegressor(n_jobs=-1, random_state=42))])

In [ ]:
# Evaluate
print("🔹 Train R²:", r2_score(y_train, model.predict(x_train)))
print("🔸 Test R²:", r2_score(y_test, model.predict(x_test)))

🔹 Train R²: 0.8643970806769048
🔸 Test R²: 0.048329761129538684

In [ ]:
# Save model + features together
save_object = {
    'model': model,
    'features': x.columns.tolist()
}
with open('model_and_features.pkl', 'wb') as f:
    pickle.dump(save_object, f)

print("✅ Model and feature list saved to model_and_features.pkl")

✅ Model and feature list saved to model_and_features.pkl